
default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  database: team_care
  username: root
  password: gyRlLNJyl3%G
  host: localhost
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default

test:
  <<: *default
  database: team_care_test
  #database: db/test.sqlite3

production:
  <<: *default
  database: team_care_production
  host: <%= Rails.application.credentials.db[:host] %>
  pool: 5
  password: <%= Rails.application.credentials.db[:password] %>

